In [10]:
import pandas as pd
import re
import string
import nltk

nltk.download("punkt")
nltk.download("stopwords")
nltk.download("wordnet")
nltk.download("omw-1.4")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\stephane.holtzmann\AppData\Roaming\nltk_data.
[nltk_data]     ..
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\stephane.holtzmann\AppData\Roaming\nltk_data.
[nltk_data]     ..
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\stephane.holtzmann\AppData\Roaming\nltk_data.
[nltk_data]     ..
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\stephane.holtzmann\AppData\Roaming\nltk_data.
[nltk_data]     ..
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [11]:
df = pd.read_csv("SMS_test.csv", encoding="latin-1")
df.head(3)

   S. No.                                       Message_body Label
0       1  UpgrdCentre Orange customer, you may now claim...  Spam
1       2  Loan for any purpose £500 - £75,000. Homeowner...  Spam
2       3  Congrats! Nokia 3650 video camera phone is you...  Spam

In [12]:
def text_lowercase(text):
    return str(text).lower()

df["Case Normalization"] = df["Message_body"].apply(text_lowercase)
df.head(3)

,S. No.,Message_body,Label,Case Normalization
0,1,"UpgrdCentre Orange customer, you may now claim...",Spam,"upgrdcentre orange customer, you may now claim..."
1,2,"Loan for any purpose £500 - £75,000. Homeowner...",Spam,"loan for any purpose £500 - £75,000. homeowner..."
2,3,Congrats! Nokia 3650 video camera phone is you...,Spam,congrats! nokia 3650 video camera phone is you...

In [13]:
import contractions

def fix_contractions(text):
    return contractions.fix(str(text))

df["Case Normalization"] = df["Case Normalization"].apply(fix_contractions)
df.head(3)

,S. No.,Message_body,Label,Case Normalization
0,1,"UpgrdCentre Orange customer, you may now claim...",Spam,"upgrdcentre orange customer, you may now claim..."
1,2,"Loan for any purpose £500 - £75,000. Homeowner...",Spam,"loan for any purpose £500 - £75,000. homeowner..."
2,3,Congrats! Nokia 3650 video camera phone is you...,Spam,congrats! nokia 3650 video camera phone is you...

In [14]:
def remove_urls(text):
    return re.sub(r"https?://\S+|www\.\S+", "", str(text))

df["Noise Removal"] = df["Case Normalization"].apply(remove_urls)
df.head(3)

,S. No.,Message_body,Label,Case Normalization,Noise Removal
0,1,"UpgrdCentre Orange customer, you may now claim...",Spam,"upgrdcentre orange customer, you may now claim...","upgrdcentre orange customer, you may now claim..."
1,2,"Loan for any purpose £500 - £75,000. Homeowner...",Spam,"loan for any purpose £500 - £75,000. homeowner...","loan for any purpose £500 - £75,000. homeowner..."
2,3,Congrats! Nokia 3650 video camera phone is you...,Spam,congrats! nokia 3650 video camera phone is you...,congrats! nokia 3650 video camera phone is you...